apiVersion: v1
kind: Service
metadata:
  labels:
    app: myflask
  name: myflask-svc
  namespace: dev-myflask
spec:
  ports:
  - name: myflask-port
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: myflask
---
apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: myflask
  name: myflask
spec:
  selector:
    matchLabels:
      app: myflask
  spec:
    containers:
    - image: ghcr.io/zuhataslan/devops21_cicd_final/my_flask:patch-v1.1.49
      name: myflask
      ports:
      - containerPort: 5000
        name: myflask-port
        protocol: TCP
  template:
    metadata:
      labels:
        app: myflask
