- op: replace
  path: /spec/template/spec/containers/0/image
  value: ghcr.io/zuhataslan/devops21_cicd_final/my_flask:latest

- op: add
  path: /spec/strategy/rollingUpdate/maxUnavailable
  value: 25%

- op: add
  path: /spec/revisionHistoryLimit
  value: 8