resources:
- ../base
namespace: prod
namePrefix: prod-

patches:
- path: deployment.yaml
  target:
    kind: Deployment 
- path: service.yaml
  target:
    kind: Service
    name: myflask-svc
    version: v1