apiVersion: v1
kind: Deployment

metadata:
  name: myflask

spec:
  selector:
    matchLabels:
      app: myflask

  template:
    metadata:
      labels:
        app: myflask

  spec:
    containers:
      - name: myflask
        ports:
          - name: myflask-port
            image: ghcr.io/zuhataslan/devops21_cicd_final/my_flask
            containerPort: 5000
            protocol: TCP


