apiVersion: apps/v1
kind: Deployment

metadata:
  name: myflask

spec:
  selector:
    matchLabels:
      app: myflask

  template:
    metadata:
      labels:
        app: myflask

    spec:
      containers:
        - name: myflask
          image: ghcr.io/zuhataslan/my_flask
          ports:
            - name: myflask-port
              containerPort: 5000
              protocol: TCP


